djangoweather/djangoweather/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from weather.views import WeatherRedirectView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("weather/", include(("weather.urls", "weather"), namespace="weather")),
    path("", WeatherRedirectView.as_view(), name="weather-redirect"),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

djangoweather/weather/urls.py
from django.urls import path
from weather.views import WeatherDataView, WeatherView

urlpatterns = [
    path("", WeatherView.as_view(), name="index"),
    path("weather_api", WeatherDataView.as_view(), name="call_weather_api"),
]

djangoweather/weather/views.py
import json
from datetime import datetime

import requests
from django.templatetags.static import static
from django.views.generic import TemplateView, RedirectView

WEATHER_API_URL = "https://api.open-meteo.com/v1/forecast?latitude={latitude}&longitude={longitude}&current=temperature_2m,is_day,precipitation,cloud_cover&hourly=temperature_2m,precipitation_probability,precipitation,cloud_cover&forecast_days=3"  # noqa: E501


class WeatherRedirectView(RedirectView):
    permanent = True
    pattern_name = "weather:index"


class WeatherView(TemplateView):
    template_name = "weather/home.html"
    site_title = "Explore the wevva!"


class WeatherDataView(TemplateView):
    template_name = "weather/weather_data.html"

    def get_timezone_from_geo_coords(self, lat, lon):
        return ""

    def call_weather_api(self):
        latitude = self.request.GET.get("lat", 0)
        longitude = self.request.GET.get("lon", 0)
        # tzone = self.get_timezone_from_geo_coords(latitude, longitude)
        url = WEATHER_API_URL.format(
            latitude=latitude,
            longitude=longitude,
        )
        weather_api_request = requests.get(url)
        json_data = {"error": "Weather API call returned a non-200 status code."}
        if weather_api_request.status_code == 200:
            json_data = json.loads(weather_api_request.content)
        # from pprint import pprint
        # pprint(json_data)
        return json_data

    def format_api_data(self, weather_data):
        weather_data = self.format_lat_lon_values(weather_data)
        weather_data = self.convert_timestamps_to_datetime(weather_data)
        weather_data = self.add_weather_icons(weather_data)
        return weather_data

    def format_lat_lon_values(self, weather_data):
        lat = weather_data["latitude"]
        lon = weather_data["longitude"]
        f_lat = f"{lat}\u00b0 N"
        f_lon = f"{lon}\u00b0 E"
        if lat < 0:
            f_lat = f"{abs(lat)}\u00b0 S"
        if lon < 0:
            f_lon = f"{abs(lon)}\u00b0 W"
        weather_data["latitude"] = f_lat
        weather_data["longitude"] = f_lon
        return weather_data

    def convert_timestamps_to_datetime(self, weather_data):
        for index, iso_timestamp in enumerate(weather_data["hourly"]["time"]):
            f_time = datetime.fromisoformat(iso_timestamp)
            weather_data["hourly"]["time"][index] = f_time
        return weather_data

    def add_weather_icons(self, weather_data):
        weather_data["hourly"]["icons"] = []
        for i in range(len(weather_data["hourly"]["time"])):
            if (
                weather_data["hourly"]["time"][i].hour > 20
                or weather_data["hourly"]["time"][i].hour < 6
            ):
                icon = static("weather/icons/moon.svg")
            else:
                icon = static("weather/icons/sun.svg")
            if weather_data["hourly"]["cloud_cover"][i] > 25:
                icon = static("weather/icons/cloud.svg")
            if weather_data["hourly"]["precipitation"][i] > 0:
                icon = static("weather/icons/cloud-drizzle.svg")
                if weather_data["hourly"]["precipitation"][i] > 2:
                    icon = static("weather/icons/cloud-rain.svg")
                if weather_data["hourly"]["temperature_2m"][i] < 0:
                    icon = static("weather/icons/cloud-snow.svg")
            weather_data["hourly"]["icons"].append(icon)

        return weather_data

    def generate_forecast(self, weather_data):
        temp = weather_data["current"]["temperature_2m"]
        forecast_map = {
            "supercold": """Oh boy, how are you still alive? Get inside quick, and have a cup of hot tea.""",
            "freezing": """Could be worse, but it's still freezing out there.
                May I suggest a nice sauna?""",
            "cold": """Not really freezing, but still kind of cold - get your sweaters and jackets ready.""",
            "warm": """Pretty warm! Some would say this is the sweet spot -
                you can walk outside with a t-shirt
                and not get sweaty just walking around. Enjoy!""",
            "hot": """It's starting to get hot - stay hydrated and seek out some shade.""",
            "superhot": """Just staying in the shade makes you sweat - be careful not to get a heat stroke!""",
            "deadlyhot": """\N{melting face} \N{melting face} \N{melting face}
                RUN. \N{melting face} \N{melting face} \N{melting face}""",
            "no_idea": "I have no idea...",
        }
        forecast_img_map = {
            "supercold": static("weather/img/supercold.jpg"),
            "freezing": static("weather/img/freezing.jpg"),
            "cold": static("weather/img/cold.jpg"),
            "warm": static("weather/img/nice.jpg"),
            "hot": static("weather/img/hot.jpeg"),
            "superhot": static("weather/img/superhot.jpg"),
            "deadlyhot": static("weather/img/deadlyhot.jpg"),
            "no_idea": static("weather/img/nice.jpg"),
        }
        chosen_forecast = None
        match temp:
            case temp if temp < -20:
                chosen_forecast = forecast_map["supercold"]
                forecast_img = forecast_img_map["supercold"]
            case temp if -20 <= temp < 0:
                chosen_forecast = forecast_map["freezing"]
                forecast_img = forecast_img_map["freezing"]
            case temp if 0 <= temp < 15:
                chosen_forecast = forecast_map["cold"]
                forecast_img = forecast_img_map["cold"]
            case temp if 15 <= temp < 25:
                chosen_forecast = forecast_map["warm"]
                forecast_img = forecast_img_map["warm"]
            case temp if 25 <= temp < 35:
                chosen_forecast = forecast_map["hot"]
                forecast_img = forecast_img_map["hot"]
            case temp if 35 <= temp < 40:
                chosen_forecast = forecast_map["superhot"]
                forecast_img = forecast_img_map["superhot"]
            case temp if temp >= 40:
                chosen_forecast = forecast_map["deadlyhot"]
                forecast_img = forecast_img_map["deadlyhot"]
            case _:
                chosen_forecast = forecast_map["no_idea"]
                forecast_img = forecast_img_map["no_idea"]
        return chosen_forecast, forecast_img

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        weather_data = self.format_api_data(self.call_weather_api())
        context["weather_data"] = weather_data
        forecast, forecast_img = self.generate_forecast(weather_data)
        context["forecast"] = forecast
        context["forecast_img"] = forecast_img
        context["hourly_forecast"] = zip(
            weather_data["hourly"]["time"],
            weather_data["hourly"]["temperature_2m"],
            weather_data["hourly"]["icons"],
        )
        return context

djangoweather/weather/templates/weather/base.html
{% comment %}
Base HTML skeleton
Includes styling (Bootstrap CSS), header, messages area, content window and footer
{% endcomment %}
<!DOCTYPE html>

{% load static %}

<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="content-type" content="text/html; charset=UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
  {% block head_load %}
  {% endblock head_load %}
  <title>{{ browser_tab_title }}</title>
</head>
<body class="mt-0">
  {### MAIN CONTENT ###}
  <div class="container">
    <nav class="navbar">
      <div class="container-fluid d-flex justify-content-center">
        <a class="navbar-brand mb-0" href="">
          <img src="{% static 'weather/icons/djangoweather.svg' %}" alt="DjangoWeather" width="150" height="56">
        </a>
      </div>
    </nav>
  </div>
  {% block content %}
  {% endblock content %}
  {### FOOTER ###}
  <ul class="nav footer d-flex justify-content-center">
    <li class="nav-item">
      <p class="footer-item-text">
        Made by rniem
      </p>
    </li>
    <li class="nav-item">
      <a class="nav-link color-primary" href="https://github.com/rniem379349/django-weather">
        <svg xmlns="http://www.w3.org/2000/svg" width="19" height="19" fill="currentColor" class="bi bi-github" viewBox="0 0 16 16">
          <path d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27s1.36.09 2 .27c1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.01 8.01 0 0 0 16 8c0-4.42-3.58-8-8-8"/>
        </svg>
        View on Github
      </a>
    </li>
  </ul>

  {% block tail_load %}
  {% endblock tail_load %}
</body>
</html>

djangoweather/weather/templates/weather/home.html
{% extends 'weather/base.html' %}
{% load static %}
{% block head_load %}
<link rel="stylesheet" href="{% static 'weather/css/weather.css' %}">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
{% endblock head_load %}

{% block content %}
<div class="map-wrapper">
    <div id="map" class="map"></div>
</div>
<div class="weather-data-container">
    <div id="weather-data">
        <p class="forecast-data">
            Click on a point on the map above to get weather information in the area, 
            plus a piece of advice depending on the weather (i.e. a humorous advisory).
        </p>
        <p class="forecast-data">
            Also, use the location button in the top right corner to center the map on your location 
            and display your local weather info. Give it a try!
        </p>
    </div>
    <div id="weather-data-loading-screen" class="d-none">
        <div id="weather-data-spinner"></div>
        <p class="loading-label">Fetching data...</p>
    </div>
</div>

{% comment %} url for weather API call {% endcomment %}
<div id="weather_api_url" style="display: none;" data-url="{% url "weather:call_weather_api" %}"></div>

<div id="geolocation-failed-snackbar" class="geolocation-snackbar align-items-center text-white bg-primary border-0 d-none">
    <div class="d-flex align-items-center">
        <div class="snackbar-icon">
            <i class="bi bi-exclamation-circle"></i>
        </div>
        <div class="snackbar-body">
            Geolocation failed. Check if you have location access blocked.
        </div>
    </div>
</div>
{% endblock content %}

{% block tail_load %}
    <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/@mojs/core"></script>
    <script>
        (g=>{var h,a,k,p="The Google Maps JavaScript API",c="google",l="importLibrary",q="__ib__",m=document,b=window;b=b[c]||(b[c]={});var d=b.maps||(b.maps={}),r=new Set,e=new URLSearchParams,u=()=>h||(h=new Promise(async(f,n)=>{await (a=m.createElement("script"));e.set("libraries",[...r]+"");for(k in g)e.set(k.replace(/[A-Z]/g,t=>"_"+t[0].toLowerCase()),g[k]);e.set("callback",c+".maps."+q);a.src=`https://maps.${c}apis.com/maps/api/js?`+e;d[q]=f;a.onerror=()=>h=n(Error(p+" could not load."));a.nonce=m.querySelector("script[nonce]")?.nonce||"";m.head.append(a)}));d[l]?console.warn(p+" only loads once. Ignoring:",g):d[l]=(f,...n)=>r.add(f)&&u().then(()=>d[l](f,...n))})({
          key: "AIzaSyB0tnlZLBa5OinIKkKkhmBSR4xBIyHJIMY",
          v: "weekly",
        });
      </script>
    <script src="{% static 'weather/js/app.js' %}"></script>
{% endblock tail_load %}

djangoweather/weather/templates/weather/weather_data.html
{% load static %}

<h2>Location: {{ weather_data.latitude }}, {{ weather_data.longitude }}</h2>
<div class="current-weather-card">
    <h2>Current Weather:</h2>
    <div class="current-weather-line">
        <p>Temperature</p>
        <h3 class="forecast-data">{{ weather_data.current.temperature_2m }} {{ weather_data.current_units.temperature_2m }}</h3>
    </div>
    <div class="current-weather-line-divider"></div>
    <div class="current-weather-line">
        <p>Precipitation</p>
        <h3 class="forecast-data">{{ weather_data.current.precipitation }} {{ weather_data.current_units.precipitation }}</h3>
    </div>
    <div class="current-weather-line-divider"></div>
    <div class="current-weather-line">
        <p>Cloud cover</p>
        <h3 class="forecast-data">{{ weather_data.current.cloud_cover }} {{ weather_data.current_units.cloud_cover }}</h3>
    </div>
</div>
<h2>Hourly Forecast:</h2>
<div class="hourly-weather-chart">
    {% for time, temp, icon in hourly_forecast %}
        {% if forloop.counter|divisibleby:3 %}
            <div class="hourly-forecast-card">
                <p class="weather-chart-day">{{ time|date:'d M' }}</p>
                <p class="weather-chart-time">{{ time|time:'h A' }}</p>
                <img src="{{ icon }}" class="weather-icon">
                <p class="weather-chart-temp">{{ temp }} &#176;C</p>
            </div>
        {% endif %}
    {% endfor %}
</div>
<h2>Advisory:</h2><p class="forecast-data">{{ forecast }}</p>
<div class="img-holder">
    <img src="{{ forecast_img }}" alt="" class="forecast-img" />
</div>